<?php $title = 'Add Gym - GymManager'; ?>

<div class="card">
    <div class="card-header">
        <h2>Add Gym</h2>
        <a href="<?= URLROOT ?>/tenants" class="btn btn-outline-primary">
            <i class="fas fa-arrow-left"></i> Back to Gyms
        </a>
    </div>
    <div class="card-body">
        <form action="<?= URLROOT ?>/tenants/store" method="post" data-validate>
            <div class="form-group">
                <label for="name">Gym Name</label>
                <input type="text" name="name" id="name" class="form-control <?= !empty($name_err) ? 'is-invalid' : '' ?>" value="<?= $name ?>" required>
                <?php if (!empty($name_err)): ?>
                    <div class="invalid-feedback"><?= $name_err ?></div>
                <?php endif; ?>
            </div>
            
            <div class="form-group">
                <label for="subdomain">Subdomain</label>
                <div class="flex align-items-center gap-1">
                    <input type="text" name="subdomain" id="subdomain" class="form-control <?= !empty($subdomain_err) ? 'is-invalid' : '' ?>" value="<?= $subdomain ?>" required>
                    <span>.yourdomain.com</span>
                </div>
                <small class="text-muted">Only lowercase letters, numbers, and hyphens allowed</small>
                <?php if (!empty($subdomain_err)): ?>
                    <div class="invalid-feedback"><?= $subdomain_err ?></div>
                <?php endif; ?>
            </div>
            
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" name="email" id="email" class="form-control <?= !empty($email_err) ? 'is-invalid' : '' ?>" value="<?= $email ?>" required>
                <?php if (!empty($email_err)): ?>
                    <div class="invalid-feedback"><?= $email_err ?></div>
                <?php endif; ?>
            </div>
            
            <div class="form-group">
                <label for="phone">Phone</label>
                <input type="text" name="phone" id="phone" class="form-control" value="<?= $phone ?>">
            </div>
            
            <div class="form-group">
                <label for="address">Address</label>
                <textarea name="address" id="address" class="form-control"><?= $address ?></textarea>
            </div>
            
            <div class="form-group">
                <label class="form-check-label">
                    <input type="checkbox" name="is_active" class="form-check-input" <?= $is_active ? 'checked' : '' ?>> 
                    Active
                </label>
            </div>
            
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Create Gym</button>
            </div>
        </form>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        const nameInput = document.getElementById('name');
        const subdomainInput = document.getElementById('subdomain');
        
        // Auto-generate subdomain from name
        nameInput.addEventListener('input', function() {
            // Only auto-generate if subdomain is empty or was auto-generated before
            if (!subdomainInput.value || subdomainInput._wasAutoGenerated) {
                const subdomain = this.value.toLowerCase()
                    .replace(/\s+/g, '-')           // Replace spaces with hyphens
                    .replace(/[^a-z0-9-]/g, '')     // Remove non-alphanumeric chars except hyphens
                    .replace(/-+/g, '-')            // Replace multiple hyphens with single one
                    .replace(/^-+|-+$/g, '');       // Trim hyphens from start and end
                
                subdomainInput.value = subdomain;
                subdomainInput._wasAutoGenerated = true;
            }
        });
        
        // When user manually changes subdomain, turn off auto-generation
        subdomainInput.addEventListener('input', function() {
            this._wasAutoGenerated = false;
        });
    });
</script>
